// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJsmjW6uFYbejRYRmkAqtxbKA4D5hkbJE',
    appId: '1:361584394408:web:2c5d4b20eef5f8aa65029d',
    messagingSenderId: '361584394408',
    projectId: 'healthform-6a3e0',
    authDomain: 'healthform-6a3e0.firebaseapp.com',
    storageBucket: 'healthform-6a3e0.appspot.com',
    measurementId: 'G-4B5563KYBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5h5IKamgYb0mzwFzEEOsd_29a34a5TpA',
    appId: '1:361584394408:android:2ad4771072d1ef2c65029d',
    messagingSenderId: '361584394408',
    projectId: 'healthform-6a3e0',
    storageBucket: 'healthform-6a3e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX_kyxTUe45mvedJEs2VR_7pNiTC0TdQM',
    appId: '1:361584394408:ios:e655a64da4d839fb65029d',
    messagingSenderId: '361584394408',
    projectId: 'healthform-6a3e0',
    storageBucket: 'healthform-6a3e0.appspot.com',
    iosBundleId: 'com.example.healthFormApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX_kyxTUe45mvedJEs2VR_7pNiTC0TdQM',
    appId: '1:361584394408:ios:f0e2a263c6a4cb4c65029d',
    messagingSenderId: '361584394408',
    projectId: 'healthform-6a3e0',
    storageBucket: 'healthform-6a3e0.appspot.com',
    iosBundleId: 'com.example.healthFormApp.RunnerTests',
  );
}
